# Generated by Django 2.2.13 on 2020-06-30 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Size', models.CharField(max_length=10)),
                ('Date_Purchased', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sold', models.BooleanField()),
                ('Date_Sold', models.DateTimeField()),
            ],
        ),
    ]
