# Generated by Django 2.2.13 on 2020-06-30 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Date_Purchased',
            new_name='date_purchased',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Sold',
            new_name='sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Date_Sold',
        ),
        migrations.AddField(
            model_name='item',
            name='date_sold',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
