# Generated by Django 2.2.13 on 2020-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200709_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_purchased',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_sold',
            field=models.DateField(auto_now_add=True),
        ),
    ]
