# Generated by Django 2.2.13 on 2020-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_sold',
            field=models.FloatField(default=0),
        ),
    ]
